FROM ministryofjustice/ruby:2.1.5

ADD https://deb.nodesource.com/gpgkey/nodesource.gpg.key /tmp/nodesource.gpg.key
RUN apt-key add /tmp/nodesource.gpg.key
RUN echo 'deb https://deb.nodesource.com/node jessie main' > /etc/apt/sources.list.d/nodesource.list

ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive

# Install required items for the build
# RUN apt-get update
# RUN apt-get install -y ...

# By copying only the Gemfile and Gemfile.lock, we make this step cacheable,
# even if other items in the source directory have changed. See
# http://ilikestuffblog.com/2014/01/06/how-to-skip-bundle-install-when-deploying-a-rails-app-to-docker/
# for more details
ADD Gemfile /tmp/gemfile-when-docker-image-built/Gemfile
ADD Gemfile.lock /tmp/gemfile-when-docker-image-built/Gemfile.lock
RUN bundle install --gemfile=/tmp/gemfile-when-docker-image-built/Gemfile
