FROM defence-request-service:latest

# For developer use only
ENV RAILS_ENV development

# Base packages:
#   - postgresql-client
# PhantomJS packages:
RUN apt-get update && apt-get -y upgrade
# Packages required for PhantomJS:
#   - build-essential
#   - chrpath
#   - git-core
#   - libssl-dev
#   - libfontconfig1-dev
RUN apt-get install -y build-essential chrpath git-core libssl-dev libfontconfig1-dev postgresql-client

###############################################################################
# Install PhantomJS
###############################################################################
ADD https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2 /usr/local/share/
RUN cd /usr/local/share/ && tar jxf /usr/local/share/phantomjs-1.9.7-linux-x86_64.tar.bz2
RUN ln -sf /usr/local/share/phantomjs-1.9.7-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs
RUN ln -sf /usr/local/share/phantomjs-1.9.7-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
RUN ln -sf /usr/local/share/phantomjs-1.9.7-linux-x86_64/bin/phantomjs /usr/bin/phantomjs

CMD "/bin/bash"

RUN apt-get -y autoremove --purge
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN truncate -s 0 /var/log/*log

VOLUME /usr/src/app
